### ISSUE TITLE
broken href in email for activity notifications

### ISSUE THREAD

**Issue by titansmc** [owncloud/activity#1103]
### Steps to reproduce
1. Owncloud 10.9
2. Share a link with someone 
3. Email will contain a broken link (without domain and probably something else)

### Expected behaviour
Link received by the user when they are notified about a shared document would work

### Actual behaviour
Email contains a broken link
```
Message-ID: <3139873ee00d2b9789abcae37ed73dc5@swift.generated>
Date: Tue, 19 Apr 2022 10:30:20 +0000
Subject: Activity notification
Auto-Submitted: auto-generated
From: ownCloud <autoreply-oc@domain.com>
To: Josep Manel Andres Moscardo <josep@domain.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_1650364220_9d91fc77d375363468cf063529b06e2a_=_"


--_=_swift_1650364220_9d91fc77d375363468cf063529b06e2a_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello Josep Manel ,

You are receiving this email becaus=
e the following things happened at /

* IT Services - Admin shared Shar=
ed/asdf.docx with you - Today at 11:24:23 AM

--
ownCloud - A safe ho=
me for all your data
https://owncloud.com

--_=_swift_1650364220_9d91fc77d375363468cf063529b06e2a_=_
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<table cellspacing=3D"0" cellpadding=3D"0" border=3D"0" width=3D"100%">
=
=09<tr><td>
=09=09=09<table cellspacing=3D"0" cellpadding=3D"0" border=3D=
"0" width=3D"600px">
=09=09=09=09<tr>
=09=09=09=09=09<td bgcolor=3D"#04=
1e42" width=3D"20px">&nbsp;</td>
=09=09=09=09=09<td bgcolor=3D"#041e42">=

=09=09=09=09=09=09<img src=3D"/core/img/logo-mail.gif" alt=3D"ownCloud"/=
>
=09=09=09=09=09</td>
=09=09=09=09</tr>
=09=09=09=09<tr><td colspan=
=3D"2">&nbsp;</td></tr>
=09=09=09=09<tr>
=09=09=09=09=09<td width=3D"20=
px">&nbsp;</td>
=09=09=09=09=09<td style=3D"font-weight:normal; font-size=
:0.8em; line-height:1.2em; font-family:verdana,'arial',sans;">
=09=09=09=
=09=09=09<p>
=09=09=09=09=09=09=09Hello Josep Manel Andres Moscardo,=09=
=09=09=09=09=09</p>
=09=09=09=09=09=09<p>
=09=09=09=09=09=09=09You are =
receiving this email because the following things happened at <a href=3D"/"=
>ownCloud</a>=09=09=09=09=09=09</p>
=09=09=09=09=09=09<ul>
=09=09=09=09=
=09=09=09=09=09=09=09=09=09=09<li>
=09=09=09=09=09=09=09=09IT Services - =
Admin shared <a href=3D"/index.php/f/23352475">Shared/asdf.docx</a> with yo=
u - Today at 11:24:23 AM=09=09=09=09=09=09=09</li>
=09=09=09=09=09=09=09=
=09=09=09=09=09=09=09=09=09=09=09=09=09</ul>
=09=09=09=09=09</td>
=09=
=09=09=09</tr>
=09=09=09=09<tr>
=09=09=09=09=09<td colspan=3D"2">&nbsp;=
</td>
=09=09=09=09</tr>
=09=09=09=09<tr>
=09=09=09=09=09<td width=3D"=
20px">&nbsp;</td>
=09=09=09=09=09<td style=3D"font-weight:normal; font-si=
ze:0.8em; line-height:1.2em; font-family:verdana,'arial',sans;">
=09=09=
=09=09=09=09--<br>
ownCloud -
A safe home for all your data<br><a href=
=3D"https://owncloud.com">https://owncloud.com</a>
=09=09=09=09=09</td>=

=09=09=09=09</tr>
=09=09=09</table>
=09=09</td></tr>
</table>

```

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 10.5.15

**PHP version:** 7.4.16

**ownCloud version:** (see ownCloud admin page) 10.9.1 Community edition

**Where did you install ownCloud from:** official link

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
[root@app13 ~]# occ app:list
Enabled:
  - activity:
    - Version: 2.7.0
    - Path: /var/www/html/owncloud/apps/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: /var/www/html/owncloud/apps/configreport
  - customgroups:
    - Version: 0.6.2
    - Path: /var/www/html/owncloud/apps/customgroups
  - dav:
    - Version: 0.7.0
    - Path: /var/www/html/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/html/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/html/owncloud/apps/files
  - files_external:
    - Version: 0.8.0
    - Path: /var/www/html/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/html/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/html/owncloud/apps/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/html/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/html/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/html/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/html/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.6.3
    - Path: /var/www/html/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/html/owncloud/apps/notifications
  - onlyoffice:
    - Version: 7.3.3
    - Path: /var/www/html/owncloud/apps/onlyoffice
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/html/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/html/owncloud/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/html/owncloud/apps/templateeditor
  - user_ldap:
    - Version: 0.16.0
    - Path: /var/www/html/owncloud/apps/user_ldap
Disabled:
  - admin_audit:
    - Path: /var/www/html/owncloud/apps/admin_audit
  - announcementcenter:
    - Path: /var/www/html/owncloud/apps/announcementcenter
  - encryption:
    - Path: /var/www/html/owncloud/apps/encryption
  - enterprise_key:
    - Path: /var/www/html/owncloud/apps/enterprise_key
  - external:
    - Path: /var/www/html/owncloud/apps/external
  - files_antivirus:
    - Path: /var/www/html/owncloud/apps/files_antivirus
  - files_classifier:
    - Path: /var/www/html/owncloud/apps/files_classifier
  - files_external_dropbox:
    - Path: /var/www/html/owncloud/apps/files_external_dropbox
  - files_external_ftp:
    - Path: /var/www/html/owncloud/apps/files_external_ftp
  - files_ldap_home:
    - Path: /var/www/html/owncloud/apps/files_ldap_home
  - files_lifecycle:
    - Path: /var/www/html/owncloud/apps/files_lifecycle
  - files_texteditor:
    - Path: /var/www/html/owncloud/apps/files_texteditor
  - firewall:
    - Path: /var/www/html/owncloud/apps/firewall
  - graphapi:
    - Path: /var/www/html/owncloud/apps/graphapi
  - guests:
    - Path: /var/www/html/owncloud/apps/guests
  - metrics:
    - Path: /var/www/html/owncloud/apps/metrics
  - oauth2:
    - Path: /var/www/html/owncloud/apps/oauth2
  - openidconnect:
    - Path: /var/www/html/owncloud/apps/openidconnect
  - password_policy:
    - Path: /var/www/html/owncloud/apps/password_policy
  - ransomware_protection:
    - Path: /var/www/html/owncloud/apps/ransomware_protection
  - sharepoint:
    - Path: /var/www/html/owncloud/apps/sharepoint
  - systemtags_management:
    - Path: /var/www/html/owncloud/apps/systemtags_management
  - theme-enterprise:
    - Path: /var/www/html/owncloud/apps/theme-enterprise
  - updatenotification:
    - Path: /var/www/html/owncloud/apps/updatenotification
  - user_external:
    - Path: /var/www/html/owncloud/apps/user_external
  - user_shibboleth:
    - Path: /var/www/html/owncloud/apps/user_shibboleth
  - web:
    - Path: /var/www/html/owncloud/apps/web
  - windows_network_drive:
    - Path: /var/www/html/owncloud/apps/windows_network_drive
  - wopi:
    - Path: /var/www/html/owncloud/apps/wopi
  - workflow:
    - Path: /var/www/html/owncloud/apps/workflow

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "516d71bc38a74",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/mnt\/owncloud\/data",
        "tempdirectory": "\/mnt\/owncloud\/data\/owncloud_tempdirectory",
        "dbtype": "mysql",
        "version": "10.9.1.2",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "loglevel": 0,
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "session_lifetime": 32400,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "oc.embl.de"
        ],
        "accounts.enable_medial_search": true,
        "updatechecker": true,
        "check_for_working_htaccess": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "mail_smtpmode": "sendmail",
        "mail_smtpdebug": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "ldapUserCleanupInterval": 5,
        "lost_password_link": "disabled",
        "singleuser": false,
        "log_type": "owncloud",
        "logfile": "\/mnt\/owncloud\/data\/owncloud.log",
        "log_rotate_size": 104857600,
        "integrity.excluded.files": [
            ".DS_Store",
            "Thumbs.db",
            ".htaccess"
        ],
        "allow_user_to_change_mail_address": ""
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 99

**Operating system:** Ubuntu 18.04 (Also happening for Windows)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"b6c9ffa8-9013-4a73-9e68-e09ff608b456","level":1,"time":"2022-04-19T11:30:29+00:00","remoteAddr":"84.153.129.87","user":"135D4DCA3E0AD89CE040010A7D016DCF","app":"onlyoffice","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Notify prepare: from josep.moscardo@embl.de about 23352475 "}
{"reqId":"T2VsrQ4hEBZUtuNLa3Nf","level":0,"time":"2022-04-19T11:30:29+00:00","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Abandoning paged search - last cookie: '', cookies: <>"}
{"reqId":"b6c9ffa8-9013-4a73-9e68-e09ff608b456","level":1,"time":"2022-04-19T11:30:29+00:00","remoteAddr":"84.153.129.87","user":"135D4DCA3E0AD89CE040010A7D016DCF","app":"onlyoffice","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Notify prepare: from josep.moscardo@embl.de about 23352475 "}
{"reqId":"T2VsrQ4hEBZUtuNLa3Nf","level":0,"time":"2022-04-19T11:30:29+00:00","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Page response cookie '' at -0, estimated<0>"}
{"reqId":"b6c9ffa8-9013-4a73-9e68-e09ff608b456","level":1,"time":"2022-04-19T11:30:29+00:00","remoteAddr":"84.153.129.87","user":"135D4DCA3E0AD89CE040010A7D016DCF","app":"onlyoffice","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Notify prepare: from josep.moscardo@embl.de about 23352475 "}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
